apiVersion: v2
name: demo-server
description: A Helm chart for Dicer Demo Server (Slicelet)
type: application
version: 0.1.0
appVersion: "1.0"
dependencies:
  - name: demo-common
    version: 0.1.0
    repository: file://../demo-common
